enum ActionTypes {
  SEND_PASSWORD_RESET_EMAIL = 'shop/ForgotPassword/SEND_PASSWORD_RESET_EMAIL',
  SEND_PASSWORD_RESET_EMAIL_SUCCESS = 'shop/ForgotPassword/SEND_PASSWORD_RESET_EMAIL_SUCCESS',
  SEND_PASSWORD_RESET_EMAIL_ERROR = 'shop/ForgotPassword/SEND_PASSWORD_RESET_EMAIL_ERROR'
}

export default ActionTypes
