enum ActionTypes {
  SEND_PASSWORD_RESET_EMAIL = 'components/App/SEND_PASSWORD_RESET_EMAIL',
  SEND_PASSWORD_RESET_EMAIL_SUCCESS = 'components/App/SEND_PASSWORD_RESET_EMAIL_SUCCESS',
  SEND_PASSWORD_RESET_EMAIL_ERROR = 'components/App/SEND_PASSWORD_RESET_EMAIL_ERROR'
}

export default ActionTypes
