enum ActionTypes {
  GET_PRODUCT_DETAIL = 'shop/Home/GET_PRODUCT_DETAIL',
  GET_PRODUCT_DETAIL_SUCCESS = 'shop/Home/GET_PRODUCT_DETAIL_SUCCESS',
  GET_PRODUCT_DETAIL_FAILED = 'shop/Home/GET_PRODUCT_DETAIL_FAILED'
}

export default ActionTypes
